name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4

      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.TOP_SECRET }}
           port: ${{ secrets.SSH_PORT }}
           script: |
            cd /var/www/html/
            git checkout -f 
            git pull origin main
